# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-24 12:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13)),
                ('full_name', models.CharField(blank=True, default='Seller', max_length=100)),
                ('location', models.CharField(blank=True, default='Kisumu', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FishCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('Tilapia', 'Tilapia'), ('Nile Perch', 'Nile Perch'), ('Dagaa', 'Dagaa'), ('Shrawl', 'Shrawl'), ('Cat Fish', 'Cat Fish')], default='Tilapia', max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Fish',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('phone_no', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, default='Kisumu', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sellers',
            },
        ),
        migrations.CreateModel(
            name='SellerPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_photo', models.ImageField(blank=True, null=True, upload_to='assets/img')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Price per Kg')),
                ('available_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('fish_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fish', to='shop.FishCategory')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Seller')),
            ],
        ),
    ]
