# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-25 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20160725_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpost',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
