# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20160726_0046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerpost',
            options={'ordering': ('-date_posted',)},
        ),
    ]
