# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20160730_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Newsletter Signups',
            },
        ),
        migrations.AddField(
            model_name='seller',
            name='times_contacted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seller',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
