# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20160730_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerInbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(max_length=13)),
                ('seller_phone', models.CharField(max_length=13)),
                ('fish_category', models.CharField(max_length=50)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.TextField(max_length=200)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Messages Sent',
                'ordering': ('-date_sent',),
            },
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name_plural': 'Newsletter'},
        ),
    ]
