# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20160730_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerinbox',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=10),
            preserve_default=False,
        ),
    ]
