# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_sellerinbox_price_per_kg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerinbox',
            old_name='message',
            new_name='message_sent',
        ),
    ]
