# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20160730_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerpost',
            options={},
        ),
    ]
